Prueba.WebApp/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Prueba.Entidades;
using Prueba.Logicas;

namespace Prueba.WebApp.Controllers
{
    public class CursoController : Controller
    {
        private CursoLogica _cursoLogica;

        #region Acciones

        public ActionResult Index()
        {
            _cursoLogica = new CursoLogica();
            return View(_cursoLogica.Listar());
        }

        public ActionResult Nuevo()
        {
            Curso model = new Curso { Activo = true };
            return View(model);
        }

        [HttpPost]
        public ActionResult Nuevo(Curso model)
        {
            _cursoLogica = new CursoLogica();
            _cursoLogica.Guardar(model);
            return RedirectToAction("Index");
        }

        public  ActionResult Editar(int id)
        {
            _cursoLogica = new CursoLogica();
            Curso model = _cursoLogica.BuscarPorId(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(Curso model)
        {
            _cursoLogica = new CursoLogica();
            _cursoLogica.Actualizar(model);
            return RedirectToAction("Index");
        }

        #endregion
    }
}

Prueba.WebApp/Views/Curso/Editar.cshtml
@model Curso
@{
    ViewBag.Title = "Nuevo Curso";
}

<div class="row">
    <div class="col-12">
        <h3 class="text-center">Editar Curso</h3>
        <hr />
    </div>
    <div class="col-12">
        @using (Html.BeginForm("Editar", "Curso", FormMethod.Post, new { }))
        {
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <label for="Descripcion">Descripción:</label>
                @Html.TextBoxFor(m => m.Descripcion, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="Credito">Credito:</label>
                @Html.TextBoxFor(m => m.Credito, new { @class = "form-control text-right" })
            </div>
            <div class="form-group">
                <label for="Activo">Activo:</label>
                @Html.CheckBoxFor(m => m.Activo)
            </div>
            <div class="form-group text-center">
                <button type="submit" class="btn btn-success">Actualizar</button>
                <a href="/Curso/Index" class="btn btn-danger">Cancelar</a>
            </div>
        }
    </div>
</div>

Prueba.WebApp/Views/Curso/Index.cshtml
@model List<Curso>
@{
    ViewBag.Title = "Lista de Cursos";
}

<div class="row">
    <div class="col-12">
        <h3 class="text-center">Lista de Cursos</h3>
        <p class="text-right">
            <a href="/Curso/Nuevo" class="btn btn-primary">Nuevo</a>
        </p>
        <hr />
    </div>
    <div class="col-12">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead class="thead-dark text-center">
                    <tr>
                        <th scope="col" width="20"></th>
                        <th scope="col" width="20">#</th>
                        <th scope="col">Descripción</th>
                        <th scope="col" width="100">Activo</th>
                    </tr>
                </thead>
                <tbody>
                    @if(Model != null && Model.Count > 0)
                    {
                        int i = 1;
                        foreach(var item in Model)
                        {
                            <tr>
                                <td>
                                    <a href="/Curso/Editar/@item.Id">Editar</a>
                                </td>
                                <td class="text-right">@(i++)</td>
                                <td>@item.Descripcion</td>
                                <td class="text-center @(item.Activo ? "text-success" : "text-danger")">@(item.Activo ? "SI" : "NO")</td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td class="text-center" colspan="4">No existen registros</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Prueba.WebApp/Views/Curso/Nuevo.cshtml
@model Curso
@{
    ViewBag.Title = "Nuevo Curso";
}


<div class="row">
    <div class="col-12">
        <h3 class="text-center">Nuevo Curso</h3>
        <hr />
    </div>
    <div class="col-12">
        @using (Html.BeginForm("Nuevo", "Curso", FormMethod.Post, new { }))
        {
            <div class="form-group">
                <label for="Descripcion">Descripción:</label>
                @Html.TextBoxFor(m => m.Descripcion, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="Credito">Credito:</label>
                @Html.TextBoxFor(m => m.Credito, new { @class = "form-control text-right" })
            </div>
            <div class="form-group">
                <label for="Activo">Activo:</label>
                @Html.CheckBoxFor(m => m.Activo)
            </div>
            <div class="form-group text-center">
                <button type="submit" class="btn btn-success">Guardar</button>
                <a href="/Curso/Index" class="btn btn-danger">Cancelar</a>
            </div>
        }
    </div>
</div>

Prueba.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Prueba</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        @Html.ActionLink("Prueba", "Index", "Curso", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/Curso/Index">Cursos <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

  

    <div class="container mt-5">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Prueba</p>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>